name: Benchmark
on:
  repository_dispatch:
    types: benchmark
jobs:
  benchmark:
    name: Benchmark
    runs-on: ubuntu-20.04
    steps:
    - name: Print Github Object
      run: 'echo "${{toJson(github)}}"'
    - uses: actions/checkout@v2
      with:
        ref: '${{ github.event.client_payload.branch }}'
    - name: Print branch
      run: |
        git rev-parse --abbrev-ref HEAD
#      - name: Do Something Based On Triggered Event Data
#        run: 'echo "Triggered event text: ${{ github.event.client_payload.text }}"'
